#!/bin/bash
# Shell script for checking Ansible roles

set -euxo pipefail

# Runs linter
make lint

# Tests for ansible take a long time to complete,
# hence it is omitted for pre-commit hooks
# make test
