---
os: linux
dist: bionic
language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
services:
  - docker
install:
  - make install
script:
  - make lint
  # Tests for ansible take a long time to complete,
  # hence it is omitted to save build minutes.
  # - make test
