---
- name: Check if CPU has virtualization extensions
  shell: grep -c -e vmx -e svm /proc/cpuinfo  # noqa: 301 305
  tags:
    # Skip check in Molecule
    - molecule-notest

- name: Check if CPU is 64-bit
  shell: grep -c -e lm /proc/cpuinfo  # noqa: 301 305
  tags:
    # Skip check in Molecule
    - molecule-notest

- name: Ensure qemu-kvm and libvirt is installed
  apt:
    name: "{{ packages }}"
    state: present
    force_apt_get: yes
  vars:
    packages:
    - qemu-kvm
    - libvirt-clients
    - libvirt-daemon-system

- name: Ensure virtinst is installed
  apt:
    name: virtinst
    state: present
    force_apt_get: yes

- name: Ensure virt-manager is installed
  apt:
    name: virt-manager
    state: present
    force_apt_get: yes
  when: not kvm_headless

- name: Ensure authorised users are added to libvirt groups
  user:
    name: "{{ item }}"
    groups:
      - libvirt
      - libvirt-qemu
    append: yes
  loop: "{{ kvm_authorised_users }}"
